services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
   # volumes:
   #   - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      # - ./custom.ini:/etc/grafana/grafana.ini
    networks:
      - monitoring

networks:
  monitoring:
    external: true
    name: 2fd26d230898f6ed4ccdcfb944eed56e6e05fa8dfdc66a82c1a3a53d7eb4e91f
volumes:
  grafana-storage: