services:
  anisfetoui-5se1-devdynamos:
    image: anisfetoui/anisfetoui-5se1-devdynamos:latest
    ports:
      - "8090:8090"
    networks:
      - network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/Coconsult?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - dbmysql

  dbmysql:
    image: mysql:8
    container_name: dbmysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - network
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=Coconsult
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - '7000:8080'
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  anisfetoui-5se1-devdynamos-frontend:
    image: anisfetoui/anisfetoui-5se1-devdynamos-coconsult-frontend:latest
    ports:
      - "4200:80"
    restart: always
    networks:
      - network
    depends_on:
      - anisfetoui-5se1-devdynamos

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    command:
      - --config.my-cnf=/cfg/.my.cnf
      - --mysqld.address=192.168.33.10:3306
    volumes:
      - "./.my.cnf:/cfg/.my.cnf"
      - "/cfg"
    ports:
      - "9104:9104"

volumes:
  db:
    external: true
networks:
  network:
    driver: bridge