services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    restart: unless-stopped

  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: unless-stopped

  dbmysql:
    image: mysql:8
    container_name: dbmysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - network
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=Coconsult
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

volumes:
  db:
networks:
  network:
    driver: bridge