version: '3'
services:
  backend:
    image: imenhadjyahya/imenhadjyahya-g7-coconsult:latest  
    container_name: backend-container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8090:8090"
    networks:
      - backend-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coconsult
    ports:
      - "3307:3306"
    networks:
      - backend-network
    volumes:
      - db-data:/var/lib/mysql  # Persistent volume for database data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend-network:
    driver: bridge

volumes:
  db-data:  # Persistent volume for MySQL
